# VERSION 1
name: Deploy API Service

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}

      - name: update main
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no root@${SERVER_IP} << 'EOF'
            cd backend/laboratory_of_python/
            git checkout main
            git pull

            # Check if this commit has a tag and deploy if it does
            if [ "$(git tag --points-at HEAD)" != "" ]; then
              cd ci_cd/basics_api_deploy
              make up_api_deploy
            else
              echo "No tags on this commit, skipping deploy."
            fi
          EOF


# VERSION 2
#name: Deploy API Service
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Setup SSH keys
#        uses: webfactory/ssh-agent@v0.9.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
#
#      - name: update main
#        run: |
#          ssh -o StrictHostKeyChecking=no root@5.35.80.39 << 'EOF'
#                      cd backend/laboratory_of_python/
#
#                      git checkout main
#                      git pull
#          EOF
#      - name: redeploy
#        run: |
#          ssh -o StrictHostKeyChecking=no root@5.35.80.39 << 'EOF'
#                      cd backend/laboratory_of_python/ci_cd/basics_api_deploy
#                      make up_api_deploy
#          EOF


## VERSION 3
#name: Deploy API Service
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  update-main:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Setup SSH keys
#        uses: webfactory/ssh-agent@v0.9.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
#
#      - name: update-main
#        run: |
#          ssh -o StrictHostKeyChecking=no root@5.35.80.39 << 'EOF'
#                      cd backend/laboratory_of_python/
#
#                      git checkout main
#                      git pull
#          EOF
#
#  deploy:
#    needs: update-main
#    runs-on: ubuntu-latest
#    steps:
#      - name: Setup SSH keys
#        uses: webfactory/ssh-agent@v0.9.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
#
#      - name: redeploy
#        run: |
#          ssh -o StrictHostKeyChecking=no root@5.35.80.39 << 'EOF'
#                      cd backend/laboratory_of_python/ci_cd/basics_api_deploy
#                      make up_api_deploy
#
#          EOF
